iastate_theme.settings:
  type: theme_settings
  label: 'Iowa State Theme Settings'
  mapping:
    isu_navbar:
      type: integer
      label: 'Show ISU navbar'
    features:
      type: mapping
      label: 'Optional features'
      mapping:
        favicon:
          type: boolean
          label: 'Use the favicon supplied by the theme'
